#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      server:
#        webflux:
#          discovery:
#            locator:
#              enabled: false
#              lower-case-service-id: true
#      routes:
#        - id: hospital-service
#          uri: lb://hospital-service
#          predicates:
#            - Path=/hospital/**
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    hostname: localhost
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
